name: AI Code Reviewer
description: "PR changes are reviewed by Gemini / OpenAI / Claude"
author: "visionworksai"

inputs:
  GEMINI_API_KEY:
    description: "Google Gemini API key"
    required: false
    default: "gemini-1.5-flash-001"

  OPENAI_API_KEY:
    description: "OpenAI API key"
    required: false
  OPENAI_MODEL:
    description: "OpenAI model name"
    required: false

  CLAUDE_API_KEY:
    description: "Anthropic Claude API key"
    required: false
  CLAUDE_MODEL:
    description: "Claude model name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Detect AI Model Type from PR comment
      id: detect_model
      run: |
        body=$(jq -r .comment.body "$GITHUB_EVENT_PATH")
        if [[ "$body" == *"/openai-review"* ]]; then
          echo "AI_MODEL_TYPE=openai" >> $GITHUB_ENV
        elif [[ "$body" == *"/claude-review"* ]]; then
          echo "AI_MODEL_TYPE=claude" >> $GITHUB_ENV
        else
          echo "AI_MODEL_TYPE=gemini" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Fail if required secret is missing
      run: |
        if [[ "$AI_MODEL_TYPE" == "openai" && -z "${{ inputs.OPENAI_API_KEY }}" ]]; then
          echo "❌ OPENAI_API_KEY is missing. Please add it to your repo secrets."
          exit 1
        elif [[ "$AI_MODEL_TYPE" == "claude" && -z "${{ inputs.CLAUDE_API_KEY }}" ]]; then
          echo "❌ CLAUDE_API_KEY is missing. Please add it to your repo secrets."
          exit 1
        elif [[ "$AI_MODEL_TYPE" == "gemini" && -z "${{ inputs.GEMINI_API_KEY }}" ]]; then
          echo "❌ GEMINI_API_KEY is missing. Please add it to your repo secrets."
          exit 1
        fi
      shell: bash
